name: Deploy Javadoc to GitHub Pages
on:
  push:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  generate-javadoc:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/gradle-generate-javadoc.yml@v1
    with:
      java-version: '21'
      gradle-arguments: aggregateJavadoc
      artifact-name: Javadoc
      cache-disabled: true
  deploy-javadoc:
    needs: [ generate-javadoc ]
    uses: Siroshun09/gh-actions-workflows/.github/workflows/deploy-to-gh-pages.yml@v1
    with:
      project-version: ${{ github.event.release.tag_name }}
      artifact-name: Javadoc
      update-latest: true
